name: train-my-model

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
   run:
     runs-on: [ubuntu-latest]
     steps:
       - uses: actions/checkout@v2
       - uses: iterative/setup-cml@v1

       #- uses: iterative/setup-dvc@v1
       #- name: Get data
       #  run: dvc pull

       - name: Train model
         run: |
           pip install -r requirements.txt  # install dependencies
           wandb disabled
           python src/models/train_model_cml.py  # run training
       - name: Write report
         env:
           # this authenticates that the right permissions are in place
           REPO_TOKEN: $
         run: |
           # send all information to report.md that will be reported to us when the workflow finish
           cat classification_report.txt >> report.md
           cml-publish confusion_matrix.png --md >> report.md
           cml-send-comment report.md
